### ISSUE TITLE
Preview of windows only works in dashboard

### ISSUE THREAD

**Issue by MagicMuscleMan** [psifidotos/workflow-project#1]
The preview of windows belonging to all activities works, if WorkFlow is shown on the dashboard (when the dashbaord is configured to show an indepenent set of plasmoids). However, it does not work if WorkFlow is on the desktop or in a panel. Then, the configuration button is greyed and cannot be activated.

**Comment by psifidotos** [comment]
This behavior was inserted in 0.2 version because I couldnt find a way to implement it.  
With its current implementation if I l let the previews in the panel the previews are shown 
behind the PopUp Applet. It must be investigated will see. Considering the Desktop case
it could be enabled but I dont know if there is a use case for Workflow in the Desktop.

In general I think it should be considered for 0.3 milestone

**Comment by psifidotos** [comment]
A question. In desktop's window are previews shown? (When you click the number of windows in a WorkArea)

**Comment by MagicMuscleMan** [comment]
I agree it is not urgent. It might be right, that Workflow does not really fit on the desktop and is much more useful on the dashboard. But as I didn't know about the dashboard (I've heard about it, but didn't think that I could make use of it), others might not know, too. So it might be a good idea to mention that maybe in the introduction you give. But this might be another issue.

To answer your question: When cklicking on the number of windows in a WorkArea, the desktop plasmoid only contains a list of window names and no previews, whereas the dashboard plasmoid contains the previews, too.

**Comment by psifidotos** [comment]
It is fixed in master, I found a solution to remove extender and use the default behavior for popupapplet...

**Comment by MagicMuscleMan** [comment]
I can confirm that it works. Thanks a lot for your great work, Michail.
