### ISSUE TITLE
Hide background

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/workflow-project#18]
--The user can choose to hide the background in order to use the default one from the theme

**Comment by mdaffin** [comment]
I would also like to see this, it will make the plasmoid fit in better with the rest of the system rather then following its own style. Especially if the user changes the plasma theme, it would make it really look out of place.

**Comment by psifidotos** [comment]
Yes, it is tracked for the next release even though I dont know about the three panels around. I will start with hiding the background and will see. ... :)

**Comment by mdaffin** [comment]
I have started a branch to experiment with removing the background (no-background), from the initial commit I feel allot of the components will need to be tweaked in order to make them look good with the default plasma theme.

I don't really feel this should be a toggleable option as kde already has a feature to change the way widget backgrounds look and feel users should use that option rather then reimplement it inside a plasmoid.

PS: Personally I would like to see you develop a plasma theme with that background and style as it is very nice but I still fell that is where it belongs, in a plasma theme

**Comment by psifidotos** [comment]
I know but no time for plasma theme in the near future...

**Comment by mdaffin** [comment]
@psifidotos how do you feel about the changes I have made to the background? Should I implement these in my data engine port as well? or reimplement the old behaviour?

**Comment by psifidotos** [comment]
I would prefer the old one james. Many things have to be done for this I think. Selecting the default colors for the various elements etc.

**Comment by mdaffin** [comment]
These will have to be tweaked anyway if you are going to have an option to disable it and then you will have to maintain two different settings for everything. Also I do feel that custom backgrounds are more suited to a plasma theme instead of a widget.

Also, I don't think that the minimal changes I made look too bad, so only a few tweaks are necessary to make it look good again.

But the final choice is up to you :)

**Comment by psifidotos** [comment]
As long as this is optional I have no problem at all, I prefer to give the user the choice because the plasma theme is so far in the future that I can not see it... :)

**Comment by psifidotos** [comment]
The changes are ready for this but for only the background... For panels I dont see something beautiful except if someone knows an interesting choice of color from the theme pallete to use it in the panels.
