### ISSUE TITLE
Usage of Graphics Areas

### ISSUE THREAD

**Issue by dovidhalevi** [psifidotos/workflow-project#25]
Current functionality may as well be a text tree view. Not as pretty much can be much more compact.

If we want to see all those (repetitive) wallpapers, then we might as well have more. Ideas:

The desktop's icons & widgets. Click/right click to do something.
Graphical placement of windows rather than text (though text is not bad).

On open area: add icon or widget?

Many more ideas will come!

**Comment by psifidotos** [comment]
[The desktop's icons & widgets. Click/right click to do something.]
I think this is a big task but I must think it. In its current state you can Add Widgets for an Activity but not from inside the plasmoid, it just opens the activity, shows the widgets explorer and hides all the windows. This is the big plus button in unlock state for an activity.

I like also the idea of Documents in Activities which is supported from KDE 4.9

[Graphical placement of windows rather than text (though text is not bad).]
You dont  mean the Desktop Dialog (by clicking the corner that shows the number of windows in a Workarea), you probably mean windows previews on the workareas.

I think that what you have in mind is different views for the WorkAreas columns (something like in Dolphin which you can select tree view, compact, previews etc.). One of the views to be the current style. I think I like a lot that approach... This gives the user the possibility to choose and fits better in more use cases. 

Important thing of course is that each view must have a mockup and use case description for the actions which should be supported before starting an implementation...

**Comment by psifidotos** [comment]
too many changes - plasmoid loses focus.....
