### ISSUE TITLE
Use system icon theme

### ISSUE THREAD

**Issue by mdaffin** [psifidotos/workflow-project#49]
Currently you can select between three different icon themes, it would be better to remove this option and just use the system icon theme.

This allows users to use icon themes that are not in the ThemeManager and makes the widget fit in better when the user uses other icon themes.

The copied icons should be removed from the project and custom icons be installed to the system icon theme rather then the plasmoid package. Then you can load all icons in the same way via QIconItem.

The use of custom icons should be considered very carefully, they break from the users icon theme making the widget look more out of place.

**Comment by psifidotos** [comment]
I know. problem was that I couldnt find a generic way for all icons theme in order to fit not perfect but at least acceptable. That was because there are many backgrounds which are not in the default theme. 

The way to go for this one I think it will be to add a 4th theme which is going to be the generic one. Just in case that someone likes it that way. It is a feature which can be added with hiding the current background in order to show the default one in the WorkAreas.

In current state when you change the kde theme the icons of course are updated. there are only very few icons which are in the plasmoid and not in the kde theme...

**Comment by mdaffin** [comment]
I am still for removing the option as there are other problems with it:
- It doesn't actually do what it says - ie it does not actually change the icon theme, just the mapping to the icons so users will not understand why nothing is changing.
- You should not have to worry about other icon themes using bad icons... that is a problem with the icon theme not the plasmoid.
- It is best to not try to remap the icons as users of the other icon theme will be use to the icons for the various tasks assuming we have picked the right icon type.

**Comment by psifidotos** [comment]
I removed all the theming functionality....
