### ISSUE TITLE
Make use of the official tooltips component

### ISSUE THREAD

**Issue by mdaffin** [psifidotos/workflow-project#58]
It would be better to make use of the official tooltips component rather then reimplementing it your self. This will decrease the amount of code you need to maintain and make the tooltips behave like the reset of the tooltips in plasma.

**Comment by psifidotos** [comment]
I agree.... DTooltip class will be removed. For the icons that are not official in the plasma theme there will be only Text version and no icon

**Comment by mdaffin** [comment]
That commit removes DToolTip completely, but there is still a bit of work in cleaning up the tooltips. I think some instances of the tooltips can be simplified such as in the activity header.

**Comment by psifidotos** [comment]
Michael I have accepted it in tempsync branch... I made some changes in order to fix issues in ActivityDeleg and WorkareaDeleg for tooltips... BIG Changes actually ... :) I cleaned up DTextLine and DTextEdit a lot, one small issue only remains in them, for some reason if the tooltip's target is whole component of DTextLine or DTextEdit the containsMouse in them is not working... The workaround is to assign to the target explicitly one of the MouseAreas in them. To make that happen I use a property called tooltipItem in them.

Before these commits I cleaned up also TaskPreviewDeleg, a very big task but one adds value to their maintenance... It was split in three classes, BasicTaskDeleg which is standalone, TaskPreviewDeleg which is standalone and ScrolledTaskPreview which uses as much functionality as possible from TaskPreviewDeleg (ScrolledTaskPreview class supports scrolling of previews in the Desktops Dialog when windows are more than 9)

**Comment by mdaffin** [comment]
This feature has not yet been merged into the master branch, it would be best to only close an issue once it is solved in the master branch (preferably via a commit message). This allows you to better track the status of the master branch and not lose issues in other branches.
